version: '3'
services:
  nginx:
    image: nginx:1.25
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./files/index.html:/usr/share/nginx/html/index.html"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
